/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import controller.Controller;
import domain.GenericEntity;
import domain.Guest;
import domain.Reservation;
import domain.Restaurant;
import domain.Table;
import domain.User;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN
 */
public class MainForm extends GenericForm {

    private User loggedUser;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setFormName();
        setLocationRelativeTo(null);
    }

    public User getLoggedUser() {
        return loggedUser;
    }

    public void setLoggedUser(User loggedUser) {
        this.loggedUser = loggedUser;
        lblLoggedUser.setText(loggedUser.getFirstName() + " " + loggedUser.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblWelcome = new javax.swing.JLabel();
        lblLoggedUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCreateRestaurant = new javax.swing.JMenuItem();
        itemAllRestaurants = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        itemCreateGuest = new javax.swing.JMenuItem();
        itemAllGuests = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setText("Zdravo,");

        lblLoggedUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoggedUser.setText("jLabel1");

        jMenu1.setText("Restorani");

        itemCreateRestaurant.setText("Kreiraj");
        itemCreateRestaurant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCreateRestaurantMouseClicked(evt);
            }
        });
        itemCreateRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateRestaurantActionPerformed(evt);
            }
        });
        jMenu1.add(itemCreateRestaurant);

        itemAllRestaurants.setText("Svi");
        itemAllRestaurants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAllRestaurantsMouseClicked(evt);
            }
        });
        itemAllRestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllRestaurantsActionPerformed(evt);
            }
        });
        jMenu1.add(itemAllRestaurants);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Stolovi");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gosti");

        itemCreateGuest.setText("Kreiraj");
        itemCreateGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCreateGuestMouseClicked(evt);
            }
        });
        itemCreateGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateGuestActionPerformed(evt);
            }
        });
        jMenu3.add(itemCreateGuest);

        itemAllGuests.setText("Svi");
        itemAllGuests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAllGuestsMouseClicked(evt);
            }
        });
        itemAllGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAllGuestsActionPerformed(evt);
            }
        });
        jMenu3.add(itemAllGuests);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Rezervacije");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Kraj");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoggedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblWelcome)
                .addGap(33, 33, 33)
                .addComponent(lblLoggedUser)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        try {
            openForm(new Table());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        try {
            openForm(new Reservation());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        end();    }//GEN-LAST:event_jMenu5MouseClicked

    private void itemAllRestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllRestaurantsActionPerformed
        try {
            new AllRestaurantsForm().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
     }//GEN-LAST:event_itemAllRestaurantsActionPerformed

    private void itemAllRestaurantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAllRestaurantsMouseClicked
        try {
            new AllRestaurantsForm().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_itemAllRestaurantsMouseClicked

    private void itemCreateRestaurantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCreateRestaurantMouseClicked
        try {
            openForm(new Restaurant());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_itemCreateRestaurantMouseClicked

    private void itemCreateGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCreateGuestMouseClicked
        try {
            new GuestForm().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemCreateGuestMouseClicked

    private void itemAllGuestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAllGuestsMouseClicked
        try {
            openForm(new Guest());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_itemAllGuestsMouseClicked

    private void itemAllGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAllGuestsActionPerformed
        try {
            new AllGuestsForm().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_itemAllGuestsActionPerformed

    private void itemCreateRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateRestaurantActionPerformed
        try {
            openForm(new Restaurant());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_itemCreateRestaurantActionPerformed

    private void itemCreateGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateGuestActionPerformed
        try {
            openForm(new Guest());
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_itemCreateGuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAllGuests;
    private javax.swing.JMenuItem itemAllRestaurants;
    private javax.swing.JMenuItem itemCreateGuest;
    private javax.swing.JMenuItem itemCreateRestaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables

    @Override
    HashMap<String, String> createObject() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    void setFormName() {
        this.setTitle("Glavna forma");
    }

    private void openForm(GenericEntity entity) throws Exception {
        GenericForm gf;
        if (entity instanceof Restaurant) {
            gf = new RestaurantForm();
        } else if (entity instanceof Table) {
            gf = new TableForm();
        } else if (entity instanceof Guest) {
            gf = new GuestForm("add");
        } else if (entity instanceof Reservation) {
            gf = new ReservationForm();
        } else {
            throw new Exception("Uneti objekat nema svoju ekransku formu");
        }
        gf.setVisible(true);
        this.setVisible(false);
        gf.main = this;
    }

    private void end() {
        try {
            Controller.getInstace().quit(loggedUser);
            dispose();
            LoginForm form = new LoginForm();
            form.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nije moguće izlogovati se u datom trenutku.");
        }
    }

    @Override
    void setTableModels() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    void populateTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    void setTools() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
